version: '3.7'

services:
  mobile:
    environment:
      - "REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP}"
      - "HOST_IP=${HOST_IP}"

    build: ./services/frontend/mobile

    command: yarn start
    volumes:
      - ./services/frontend/mobile/:/usr/src/app/

    ports:
      - 19000:19000
      - 19001:19001
      - 19006:19006
      
    depends_on:
      - web

  web:
    # Build directory relative to compose file
    build: ./services/web

    environment: 
      - "HOST_IP=${HOST_IP}"

    # Python command to run service
    command: python manage.py run -h 0.0.0.0
    volumes:
      # Bind web directory to usr/src/app/ inside container
      - ./services/web/:/usr/src/app/
    ports:
      # Port binding
      - 5000:5000
    env_file:
      # File to configure environment variables 
      - ./.env.dev
 # Postgres DB image
    depends_on:
      - db
  db:
    # Docker image pulled for container
    image: postgres:12.0-alpine
    volumes:
      # Store db data at this location inside container
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # User, Password, and DB name
      - POSTGRES_USER=envirohome_db
      - POSTGRES_PASSWORD=envirohome_db
      - POSTGRES_DB=envirohome_db_dev
  eventstore.db:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"

volumes:
  postgres_data: